GET http://localhost:5000/660/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldkB0ZXN0LmNvbSIsImlhdCI6MTcwNjYwNjg3NCwiZXhwIjoxNzA2NjEwNDc0LCJzdWIiOiIxIn0.S2Wz8WRDxIaQoChU-h_ggD1pRgqf_X30s_lFr-txrZU

